Changing billing cycle no longer requires cancelling first
teamgantt/dues pull request #37
Opened 2022-01-20 19:19 UTC by brianium

2022-01-20 19:20 UTC, brianium commented on src/Processor/Braintree/Subscription/Update/ChangeBillingCycleStrategy.php
> +        return new AddOn('overdue', 1, new Price(abs($fuzzy)));
@johncorrelli we don't have a test case for this in the suite, but we never did. Can you spot check this for correctness?

2022-01-24 19:05 UTC, johncorrelli requested changes
Nice work homie! Just a few little things. Most importantly around a subscription without a price and the function naming on the billing period.

2022-01-24 19:05 UTC, johncorrelli commented on src/Processor/Braintree/Mapper/SubscriptionMapper.php
> +        return $sub->setRemainingValue($remainingValue);
should we avoid the assignment/reassignment and do....

```php
 $remainingValue = round($costPerDay * $remainingCycle, 2);

return $sub->setRemainingValue(new Money($remainingValue));
```

2022-01-24 21:05 UTC, brianium commented on src/Model/Subscription/BillingPeriod.php
> +    public function getBillingCycle(): int
Braintree just called it cycle. A doc block sounds good to me

2022-01-24 21:23 UTC, brianium commented on src/Model/Modifier/Modifier.php
> +        if (null == $price) {
Guess not! I can change it though 🤷🏻

2022-02-07 17:52 UTC, brianium commented on src/Model/Subscription.php
> +        }
@johncorrelli please check out what I did instead with regards to this.

2022-02-08 14:33 UTC, johncorrelli approved these changes
:boom: Looks great man! And lovin' the automated tests we have in place now! :heart:

2022-02-08 14:37 UTC, merged

2022-02-08 14:38 UTC, johncorrelli commented on src/Model/Subscription.php
> +        }
Looks good to me! Now you can have a subscription without a price, but the modifiers can drive the actual amount that is being charged. :heart: